---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        # href: http://localhost/
        description: Homepage is 😎
        widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
